# NumPy Practice

In [16]:
import numpy as np
#my_array = np.array (5,2)
#my_array = np.arange (100, 200, 10)
my_array = np.array([np.arange (100, 120, 10),np.arange (120, 140, 10), np.arange (140, 160, 10),np.arange (160, 180, 10),np.arange (180, 200, 10)])
print (my_array)
print (my_array.shape)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]
(5, 2)


In [64]:
import numpy as np
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
#print (sampleArray[0:3][3:])

#Transposing the matrix
newsampleArray = sampleArray.transpose()
print (newsampleArray[2])


[33 66 99]


In [82]:
import numpy
from math import sqrt

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
print (arrayOne)
print("\n")
print (arrayTwo)
print("\n")

#Addition of the two arrays
arrayThree = arrayOne + arrayTwo
print (arrayThree)
print("\n")
print (arrayThree*arrayThree)
print("\n")
print (pow(arrayThree,1/2))

[[ 5  6  9]
 [21 18 27]]


[[15 33 24]
 [ 4  7  1]]


[[20 39 33]
 [25 25 28]]


[[ 400 1521 1089]
 [ 625  625  784]]


[[4.47213595 6.244998   5.74456265]
 [5.         5.         5.29150262]]
